name 'forest_monitor'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures forest_monitor'
long_description 'Installs/Configures forest_monitor'
version '0.1.0'
